INSERT INTO ENDERECO VALUES (1, 'Rua Frederico Lopez', 'Jardim Brasil','Londrina');
INSERT INTO ENDERECO VALUES (2, 'Milesio', 'Deodoro', 'Londrina');
INSERT INTO ENDERECO VALUES (3, 'Rua Frederico Lopez', 'Jardim Brasil','Londrina');
INSERT INTO ENDERECO VALUES (4, 'Milesio', 'Deodoro', 'Londrina');
INSERT INTO ENDERECO VALUES (5, 'Rua das Flores', 'Centro', 'Londrina');
INSERT INTO ENDERECO VALUES (6, 'Rua dos Girassóis', 'Vila Nova', 'Londrina');
INSERT INTO ENDERECO VALUES (7, 'Rua das Flores', 'Centro', 'Ibiporã');
INSERT INTO ENDERECO VALUES (8, 'Avenida Principal', 'Jardim', 'Cambé');
INSERT INTO ENDERECO VALUES (9, 'Rua dos Girassóis', 'Centro', 'Cambé');
INSERT INTO ENDERECO VALUES (10, 'Rua das Palmeiras', 'Centro', 'Ibiporã');
INSERT INTO ENDERECO VALUES (11, 'Avenida das Árvores', 'Jardim', 'Londrina');
INSERT INTO ENDERECO VALUES (12, 'Rua dos Ipês', 'Bairro Novo', 'Londrina');
INSERT INTO ENDERECO VALUES (13, 'Avenida dos Coqueiros', 'Praia', 'Jataizinho');
INSERT INTO ENDERECO VALUES (14, 'Rua das Castanheiras', 'Centro', 'Ibiporã');
INSERT INTO ENDERECO VALUES (15, 'Avenida das Flores', 'Jardim', 'Londrina');
INSERT INTO ENDERECO VALUES (16, 'Rua dos Flamboyants', 'Bairro Novo', 'Cambé');
INSERT INTO ENDERECO VALUES (17, 'Rua das Azaleias', 'Jardim Primavera', 'Londrina');
INSERT INTO ENDERECO VALUES (18, 'Rua das Orquídeas', 'Centro', 'Londrina');
INSERT INTO ENDERECO VALUES (19, 'Avenida dos Pinheiros', 'Jardim das Oliveiras', 'Ibiporã');
INSERT INTO ENDERECO VALUES (20, 'Rua dos Jacarandás', 'Vila Nova', 'Cambé');
INSERT INTO ENDERECO VALUES (21, 'Rua das Hortênsias', 'Jardim Europa', 'Londrina');
INSERT INTO ENDERECO VALUES (22, 'Rua das Begônias', 'Centro', 'Londrina');
INSERT INTO ENDERECO VALUES (23, 'Avenida dos Eucaliptos', 'Jardim América', 'Ibiporã');
INSERT INTO ENDERECO VALUES (24, 'Rua das Violetas', 'Vila Rica', 'Cambé');
INSERT INTO ENDERECO VALUES (25, 'Avenida das Acácias', 'Jardim Tropical', 'Jataizinho');

INSERT INTO MATERIA VALUES (1, 'Matemática', 60);
INSERT INTO MATERIA VALUES (2, 'Português', 50);
INSERT INTO MATERIA VALUES (3, 'Ciências', 45);
INSERT INTO MATERIA VALUES (4, 'História', 40);
INSERT INTO MATERIA VALUES (5, 'Geografia', 40);
INSERT INTO MATERIA VALUES (6, 'Inglês', 50);
INSERT INTO MATERIA VALUES (7, 'Artes', 35);
INSERT INTO MATERIA VALUES (8, 'Educação Física', 15);
INSERT INTO MATERIA VALUES (9, 'Ensino Religioso', 20);

INSERT INTO TURMA VALUES (1, '1A', 2005);
INSERT INTO TURMA VALUES (2, '1B', 2005);
INSERT INTO TURMA VALUES (3, '2A', 2004);
INSERT INTO TURMA VALUES (4, '2B', 2004);
INSERT INTO TURMA VALUES (5, '3A', 2003);
INSERT INTO TURMA VALUES (6, '3B', 2003);

INSERT INTO ALUNO VALUES (1, 'João Victor', 'joao@edu.com', 'CEL','(43)98455-9021', 'N', 2, 1);
INSERT INTO ALUNO VALUES (2, 'Maria Luiza', 'maria@edu.com', 'RES','(43)3209-8723', 'S', 6, 2);
INSERT INTO ALUNO VALUES (3, 'Ana Silva', 'ana@edu.com', 'RES','(43)3309-7712', 'N', 3, 19);
INSERT INTO ALUNO VALUES (4, 'Carlos Santos', 'carlos@edu.com', 'COM','(43)99210-3321', 'S', 1, 4);
INSERT INTO ALUNO VALUES (5, 'Lucas Oliveira', 'lucas@edu.com', 'RES','(43)3310-9843', 'N', 1, 5);
INSERT INTO ALUNO VALUES (6, 'Fernanda Costa', 'fernanda@edu.com', 'CEL','(43)99876-5432', 'N', 2, 6);
INSERT INTO ALUNO VALUES (7, 'Mateus Lima', 'mateus@edu.com', 'RES','(43)3201-1234', 'S', 2, 7);
INSERT INTO ALUNO VALUES (8, 'Juliana Almeida', 'juliana@edu.com', 'COM','(43)3355-6789', 'N', 2, 8);
INSERT INTO ALUNO VALUES (9, 'Gabriel Martins', 'gabriel@edu.com', 'CEL','(43)99123-4567', 'N', 3, 9);
INSERT INTO ALUNO VALUES (10, 'Mariana Silva', 'mariana@edu.com', 'RES','(43)3300-2222', 'N', 1, 10);
INSERT INTO ALUNO VALUES (11, 'Paulo Souza', 'paulo@edu.com', 'COM','(43)99999-9999', 'N', 6, 11);
INSERT INTO ALUNO VALUES (12, 'Cristina Oliveira', 'cristina@edu.com', 'CEL','(43)98888-8888', 'N', 3, 12);
INSERT INTO ALUNO VALUES (13, 'Rodrigo Santos', 'rodrigo@edu.com', 'CEL','(43)97777-7777', 'N', 2, 13);
INSERT INTO ALUNO VALUES (14, 'Aline Pereira', 'aline@edu.com', 'RES','(43)96666-6666', 'N', 1, 14);
INSERT INTO ALUNO VALUES (15, 'Fernando Oliveira', 'fernando@edu.com', 'COM','(43)95555-5555', 'N', 3, 15);
INSERT INTO ALUNO VALUES (16, 'Patrícia Lima', 'patricia@edu.com', 'CEL','(43)94444-4444', 'N', 4, 16);
INSERT INTO ALUNO VALUES (17, 'Rafaela Almeida', 'rafaela@edu.com', 'RES','(43)93333-3333', 'N', 4, 17);
INSERT INTO ALUNO VALUES (18, 'Vinicius Martins', 'vinicius@edu.com', 'CEL','(43)92222-2222', 'N', 4, 18);
INSERT INTO ALUNO VALUES (19, 'Beatriz Silva', 'beatriz@edu.com', 'COM','(43)91111-1111', 'N', 4, 19);
INSERT INTO ALUNO VALUES (20, 'Ricardo Souza', 'ricardo@edu.com', 'RES','(43)90000-0000', 'S', 5, 20);
INSERT INTO ALUNO VALUES (21, 'Isabela Oliveira', 'isabela@edu.com', 'RES','(43)88888-8888', 'N', 5, 23);
INSERT INTO ALUNO VALUES (22, 'Eduardo Santos', 'eduardo@edu.com', 'COM','(43)87777-7777', 'N', 5, 20);
INSERT INTO ALUNO VALUES (23, 'Camila Pereira', 'camila@edu.com', 'CEL','(43)86666-6666', 'N', 5, 19);
INSERT INTO ALUNO VALUES (24, 'Leonardo Lima', 'leonardo@edu.com', 'RES','(43)85555-5555', 'N', 5, 22);
INSERT INTO ALUNO VALUES (25, 'Julia Almeida', 'julia@edu.com', 'COM','(43)84444-4444', 'S', 4, 21);
INSERT INTO ALUNO VALUES (26, 'Marcelo Oliveira', 'marcelo@edu.com', 'COM','(43)83333-3333', 'N', 6, 25);
INSERT INTO ALUNO VALUES (27, 'Isadora Lima', 'isadora@edu.com', 'CEL','(43)82222-2222', 'N', 6, 18);
INSERT INTO ALUNO VALUES (28, 'Bruno Silva', 'bruno@edu.com', 'RES','(43)81111-1111', 'N', 6, 17);
INSERT INTO ALUNO VALUES (29, 'Laura Souza', 'laura@edu.com', 'COM','(43)80000-0000', 'S', 3, 16);
INSERT INTO ALUNO VALUES (30, 'Renan Santos', 'renan@edu.com', 'CEL','(43)77777-7777', 'N', 1, 24);

INSERT INTO PROFESSOR VALUES (1, 'Pedro Dias', 'pedro@edu.com', 'CEL','(43)99934-0298', 9, 24);
INSERT INTO PROFESSOR VALUES (2, 'Ana Carilia', 'ana@edu.com', 'COM','(43)3405-9306', 8, 2);
INSERT INTO PROFESSOR VALUES (3, 'Lucas Ferreira', 'lucasferreira@edu.com', 'CEL','(43)99444-4444', 7, 13);
INSERT INTO PROFESSOR VALUES (4, 'Patrícia Santos', 'patricia@edu.com', 'COM','(43)3333-3333', 6, 12);
INSERT INTO PROFESSOR VALUES (5, 'Roberto Lima', 'roberto@edu.com', 'RES','(43)3222-2222', 5, 5);
INSERT INTO PROFESSOR VALUES (6, 'Mariana Costa', 'mariana@edu.com', 'CEL', '(43)98765-4321', 4, 6);
INSERT INTO PROFESSOR VALUES (7, 'Ricardo Oliveira', 'ricardo@edu.com', 'RES', '(43)98765-4322', 3, 7);
INSERT INTO PROFESSOR VALUES (8, 'Amanda Silva', 'amanda@edu.com', 'CEL', '(43)98765-4323', 2, 2);
INSERT INTO PROFESSOR VALUES (9, 'Fernanda Sousa', 'fernanda@edu.com', 'CEL', '(43)98765-4324', 1, 9);

INSERT INTO SEMANA VALUES (1, 'Segunda-Feira', '1ª aula', 2);
INSERT INTO SEMANA VALUES (2, 'Segunda-Feira', '2ª aula', 1);
INSERT INTO SEMANA VALUES (3, 'Segunda-Feira', '3ª aula', 4);
INSERT INTO SEMANA VALUES (4, 'Segunda-Feira', '4ª aula', 3);
INSERT INTO SEMANA VALUES (5, 'Terça-Feira', '1ª aula', 1);
INSERT INTO SEMANA VALUES (6, 'Terça-Feira', '2ª aula', 2);
INSERT INTO SEMANA VALUES (7, 'Terça-Feira', '3ª aula', 6);
INSERT INTO SEMANA VALUES (8, 'Terça-Feira', '4ª aula', 3);
INSERT INTO SEMANA VALUES (9, 'Quarta-Feira', '1ª aula', 5);
INSERT INTO SEMANA VALUES (10, 'Quarta-Feira', '2ª aula', 4);
INSERT INTO SEMANA VALUES (11, 'Quarta-Feira', '3ª aula', 1);
INSERT INTO SEMANA VALUES (12, 'Quarta-Feira', '4ª aula', 2);
INSERT INTO SEMANA VALUES (13, 'Quinta-Feira', '1ª aula', 1);
INSERT INTO SEMANA VALUES (14, 'Quinta-Feira', '2ª aula', 7);
INSERT INTO SEMANA VALUES (15, 'Quinta-Feira', '3ª aula', 2);
INSERT INTO SEMANA VALUES (16, 'Quinta-Feira', '4ª aula', 3);
INSERT INTO SEMANA VALUES (17, 'Sexta-Feira', '1ª aula', 1);
INSERT INTO SEMANA VALUES (18, 'Sexta-Feira', '2ª aula', 9);
INSERT INTO SEMANA VALUES (19, 'Sexta-Feira', '3ª aula', 6);
INSERT INTO SEMANA VALUES (20, 'Sexta-Feira', '4ª aula', 8);

INSERT INTO AULA VALUES (1, '2024-03-21', 2);
INSERT INTO AULA VALUES (2, '2024-03-21', 1);
INSERT INTO AULA VALUES (3, '2024-03-21', 4);
INSERT INTO AULA VALUES (4, '2024-03-21', 3);
INSERT INTO AULA VALUES (5, '2024-03-22', 1);
INSERT INTO AULA VALUES (6, '2024-03-22', 2);
INSERT INTO AULA VALUES (7, '2024-03-22', 6);
INSERT INTO AULA VALUES (8, '2024-03-22', 3);

INSERT INTO CHAMADA VALUES (1, 1, 'S');
INSERT INTO CHAMADA VALUES (1, 2, 'S');
INSERT INTO CHAMADA VALUES (1, 3, 'S');
INSERT INTO CHAMADA VALUES (1, 4, 'S');
INSERT INTO CHAMADA VALUES (1, 5, 'S');
INSERT INTO CHAMADA VALUES (1, 6, 'S');
INSERT INTO CHAMADA VALUES (1, 7, 'N');
INSERT INTO CHAMADA VALUES (1, 8, 'N');
INSERT INTO CHAMADA VALUES (1, 9, 'S');
INSERT INTO CHAMADA VALUES (1, 10, 'N');
INSERT INTO CHAMADA VALUES (1, 11, 'S');
INSERT INTO CHAMADA VALUES (1, 12, 'S');
INSERT INTO CHAMADA VALUES (1, 13, 'N');
INSERT INTO CHAMADA VALUES (1, 14, 'S');
INSERT INTO CHAMADA VALUES (1, 15, 'S');
INSERT INTO CHAMADA VALUES (1, 16, 'S');
INSERT INTO CHAMADA VALUES (1, 17, 'N');
INSERT INTO CHAMADA VALUES (1, 18, 'N');
INSERT INTO CHAMADA VALUES (1, 19, 'S');
INSERT INTO CHAMADA VALUES (1, 20, 'S');
