CREATE TABLE ALUNO (
    IDAluno INT,    
    Nome VARCHAR(80) NOT NULL UNIQUE,
    Email VARCHAR(80) NOT NULL UNIQUE,
    Tipo ENUM ('CEL', 'COM', 'RES') NOT NULL,
    Numero VARCHAR(30) NOT NULL UNIQUE,
    Representante ENUM ('S', 'N') NOT NULL,
    ID_Turma INT NOT NULL,
    ID_Endereco INT NOT NULL,
    PRIMARY KEY (IDAluno)
);

CREATE TABLE TURMA (
    IDTurma INT,
    NomeTurma CHAR(2) NOT NULL UNIQUE,
    Ano INT NOT NULL,
    PRIMARY KEY (IDTurma)
);

CREATE TABLE PROFESSOR (
    IDProfessor INT,
    Nome VARCHAR(80) NOT NULL UNIQUE,
    Email VARCHAR(80) NOT NULL UNIQUE,
    Tipo ENUM ('CEL', 'COM', 'RES') NOT NULL,
    Numero VARCHAR(30) NOT NULL UNIQUE,
    ID_Materia INT NOT NULL,
    ID_Endereco INT NOT NULL,
    PRIMARY KEY (IDProfessor)
);

CREATE TABLE ENDERECO (
    IDEndereco INT,
    Rua VARCHAR(80) NOT NULL,
    Bairro VARCHAR(80) NOT NULL,
    Cidade VARCHAR(80) NOT NULL,
    PRIMARY KEY (IDEndereco)
);

CREATE TABLE MATERIA (
    IDMateria INT,
    Nome VARCHAR(80) NOT NULL UNIQUE,
    CargaHoraria INT NOT NULL,
    PRIMARY KEY (IDMateria)
);

CREATE TABLE SEMANA (
    IDSemana INT,
    DiaSemana VARCHAR(15) NOT NULL,
    OrdemAula VARCHAR(15) NOT NULL,
    ID_Materia INT NOT NULL,
    PRIMARY KEY (IDSemana)
);

CREATE TABLE AULA (
    IDAula INT,
	Data DATE NOT NULL,
    ID_Materia INT,
    PRIMARY KEY (IDAula)
);

CREATE TABLE CHAMADA (
    ID_Aula INT,
    ID_Aluno INT,
    Presenca ENUM ('S', 'N') NOT NULL,
    PRIMARY KEY (ID_Aula, ID_Aluno)
);

ALTER TABLE ALUNO
    ADD FOREIGN KEY (ID_Endereco) REFERENCES ENDERECO(IDEndereco),
    ADD FOREIGN KEY (ID_Turma) REFERENCES TURMA(IDTurma);

ALTER TABLE PROFESSOR
    ADD FOREIGN KEY (ID_Endereco) REFERENCES ENDERECO(IDEndereco),
    ADD FOREIGN KEY (ID_Materia) REFERENCES MATERIA(IDMateria);
	
ALTER TABLE TURMA
    ADD FOREIGN KEY (ID_Aluno) REFERENCES ALUNO(IDAluno);
	
ALTER TABLE SEMANA
    ADD FOREIGN KEY (ID_Materia) REFERENCES MATERIA(IDMateria);	

ALTER TABLE AULA
    ADD FOREIGN KEY (ID_Materia) REFERENCES MATERIA(IDMateria);

ALTER TABLE CHAMADA
    ADD FOREIGN KEY (ID_Aula) REFERENCES AULA(IDAula),
    ADD FOREIGN KEY (ID_Aluno) REFERENCES ALUNO(IDAluno);

